-- MySQL Script generated by MySQL Workbench
-- Mon Jun 18 11:37:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `parking` ;

-- -----------------------------------------------------
-- Schema parking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parking` DEFAULT CHARACTER SET utf8 ;
USE `parking` ;

-- -----------------------------------------------------
-- Table `parking`.`preco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`preco` ;

CREATE TABLE IF NOT EXISTS `parking`.`preco` (
  `preco_id` INT NOT NULL AUTO_INCREMENT,
  `minutos` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`preco_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking`.`movimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`movimento` ;

CREATE TABLE IF NOT EXISTS `parking`.`movimento` (
  `movimento_id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `entrada` DATETIME NOT NULL,
  `saida` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`movimento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking`.`tipo_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`tipo_veiculo` ;

CREATE TABLE IF NOT EXISTS `parking`.`tipo_veiculo` (
  `tipo_veiculo_id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`tipo_veiculo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`marca` ;

CREATE TABLE IF NOT EXISTS `parking`.`marca` (
  `marca_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`marca_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking`.`teste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`teste` ;

CREATE TABLE IF NOT EXISTS `parking`.`teste` (
  `teste_id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`teste_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`usuario` ;

CREATE TABLE IF NOT EXISTS `parking`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `status` SMALLINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
